export const SN_UTIL = 'util'
export const UTIL_SHIPMENT_METHODS_UPDATED = SN_UTIL + '/SHIPMENT_METHODS_UPDATED'
export const UTIL_STATUS_UPDATED = SN_UTIL + '/STATUS_UPDATED'
export const UTIL_SHPMNT_MTHD_BY_CARRIER_UPDATED = SN_UTIL + '/SHPMNT_MTHD_BY_CARRIER_UPDATED'