export default {
  "APP_COMMERCE_VIEW": "APP_COMMERCE_VIEW",
  "APP_PRODUCT_IDENTIFIER_UPDATE": "APP_PRODUCT_IDENTIFIER_UPDATE",
  "APP_PWA_STANDALONE_ACCESS": "APP_PWA_STANDALONE_ACCESS",
  "APP_BULK_UPLOAD": "APP_TFNR_BULK_UPLOAD",
  "APP_DISCREPANCY_REPORT": "APP_TFNR_DISCREPANCY_REPORT"
}