export default {
  "TRANSFERS_APP_VIEW": "TRANSFERS_APP_VIEW OR COMMON_ADMIN",
  "APP_COMMERCE_VIEW": "COMMERCEUSER_VIEW",
  "APP_PRODUCT_IDENTIFIER_UPDATE":"COMMON_ADMIN",
  "APP_PWA_STANDALONE_ACCESS": "COMMON_ADMIN",
  "APP_BULK_UPLOAD": "APP_TFNR_BULK_UPLOAD",
  "APP_DISCREPANCY_REPORT": "APP_TFNR_DISCREPANCY_REPORT"
} as any